Demand/urls.py
from django.conf.urls import url
from views import  DemandCreateView, DemandListView

app_name = 'Demand'

urlpatterns = [
    url(r'^$', DemandListView.as_view(), name="Index"),
    url(r'^Create/', DemandCreateView.as_view(), name="Create")

]

DemandManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from Demand.views import MainPage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'), 
    url(r'^$', MainPage.as_view(), name='Welcome'),
    url(r'^DemandManagement/', include('Demand.urls')),
    url(r'^Engagement/', include('Engagement.urls')),
    url(r'^Survey/', include('Survey.urls')),
]

Survey/urls.py
from django.conf.urls import url
from views import NewQuestion, AllQuestions, ViewQuestion, UpdateQuestion, NewSurvey, FillSurvey, AllSurveys
app_name = 'Survey'

urlpatterns = [
    url(r'^$', AllSurveys.as_view(), name='Index'),
    url(r'^Create/$', NewQuestion.as_view(), name="Create"),
    url(r'^Questions/$', AllQuestions.as_view(), name='Questions'),
    url(r'^Question/(?P<pk>\d+)/$', ViewQuestion.as_view(), name='Details'),
    url(r'^Update/(?P<pk>\d+)/$',  UpdateQuestion.as_view(), name='Edit'),
    url(r'^NewSurvey/$', NewSurvey.as_view(), name='NewSurvey'),
    url(r'^Survey/(?P<pk>\d+)/$',  FillSurvey.as_view(), name='Survey'), 
]

Survey/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from Engagement.models import SubProject, Activity

# Create your models here.

class Section(models.Model):
    Name = models.CharField(max_length = 100)
    Title = models.CharField(max_length = 100)
    Subheading = models.CharField(max_length = 256, blank = True, null= True)

    def __str__(self):
        return self.Name

class InputType(models.Model):
    Name = models.CharField(max_length = 50)
    
    def __str__(self):
        return self.Name


class Option(models.Model):
    Value = models.CharField(max_length=256)
    def __str__(self):
        return self.Value


class OptionGroup(models.Model):
    Name = models.CharField(max_length=75)
    Options = models.ManyToManyField(Option)
    def __str__(self):
        return self.Name

class Unit(models.Model):
    Name = models.CharField(max_length = 50)
    def __str__(self):
        return self.Name
    
class Question(models.Model):
    Section = models.ForeignKey(Section)
    InputType = models.ForeignKey(InputType)
    Text = models.CharField(max_length = 256)
    AnswerRequired = models.BooleanField(default=False, blank=False, null=False)
    MultipleAnswers = models.BooleanField(default=False, blank=False, null=False)
    OptionGroup = models.ForeignKey(OptionGroup,blank=True, null=True)
    Unit = models.ForeignKey(Unit, blank=True, null=True)

    def __str__(self):
        return self.Text

class QuestionSet(models.Model):
    Name = models.CharField(max_length = 256)
    Questions = models.ManyToManyField(Question)
    DefaultFor = models.OneToOneField(Activity, null=True, blank=True)

    def __str__(self):
        return self.Name

class Survey(models.Model):
    Respondent = models.ForeignKey(User)
    Engagement = models.ForeignKey(SubProject)
    QuestionSet = models.ForeignKey(QuestionSet)

    def __str__(self):
        return self.Engagement.Name + ' - ' + self.QuestionSet.Name

class Answer(models.Model):
    Question = models.ForeignKey(Question)
    Survey = models.ForeignKey(Survey, null=True)
    Options = models.ManyToManyField(Option, blank=True)
    Numeric = models.FloatField(null=True, blank=True)
    Text = models.CharField(max_length = 1000, null = True, blank=True)
    Bool = models.NullBooleanField( null = True, blank=True)
    
    
    def __str__(self):
        question = self.Question.Text
        if not self.Text is None:
            return question + ' - ' + self.Text
        if not self.Numeric is None:
            return question + ' - ' + str(self.Numeric)
        if not self.Bool is None: 
            return question + ' - ' + str(self.Bool)

        return question + ' - ' + 'No answer specified delete or fix.'
    

Survey/forms.py
from django.forms import inlineformset_factory
from models import Question, QuestionSet, Option, Answer

Survey/views.py
from django.shortcuts import render
from django import template
from django.http import HttpResponse
from django.contrib import messages
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.views.generic import UpdateView, CreateView, ListView, DetailView
from models import Question, Answer, Option, OptionGroup, QuestionSet, Survey
from templatetags import SurveyExtras
# Create your views here.


def GetFormOptions(request):
    return [o for o in request.POST.getlist('Options')]

def DefaultList(request):
    defaultList = []
    for q in QuestionSet.objects.all():
        if not q.DefaultFor is None:
            defaultList.append(str(q.DefaultFor.pk))
    return defaultList

def GetOption(value):
    return Option.objects.get(Value=value)

def GetQuestion(pk):
    return Question.objects.get(pk=pk)

def GetInstanceOptionGroup(form):
    question = get_object_or_404(Question, pk=form.instance.pk)
    return question.OptionGroup

class NewSurvey(CreateView):
    model = QuestionSet
    fields = ('Name', 'DefaultFor')
    template_name = 'Survey/CreateSurvey.html'
    context_object_name = 'Survey'
    success_url = "/Survey/NewSurvey/"

    def Questions(self):
        return Question.objects.all()

    def form_valid(self, form):
        questionSet = form.instance
        questionSet.save()
        for option in self.request.POST.getlist('selectedQuestions'):
            questionSet.Questions.add(GetQuestion(option))
        form.save()
        return super(NewSurvey, self).form_valid(form)

    def form_invalid(self, form):
        response = super(NewSurvey, self).form_invalid(form)
        req = self.request
        defaultsUsed = DefaultList(self.request)
        if req.POST.get('DefaultFor') in defaultsUsed:
            messages.error(req, 'This Activity already has a default survey, leave the ')
        if req.POST.get('Name') is None:
            messages.error(req, 'No Name specified')
        return response

class FillSurvey(UpdateView):
    model = Survey
    fields = ()
    template_name = 'Survey/Survey.html'
    context_object_name = 'Survey'
    success_url = "/Survey/"

    def Answers(self):
        return Answer.objects.filter(Survey=self.kwargs['pk'])

    def form_valid(self, form):
        Questions = form.instance.QuestionSet.Questions.all()
        request = self.request.POST
        form.clean()
        for question in Questions:
            if request.__contains__(str(question.pk)) and request.get(str(question.pk)) != '':
                if Answer.objects.filter(Question = question.pk, Survey = form.instance.pk).exists():
                    newAnswear = Answer.objects.get(Question=question.pk, Survey=form.instance.pk)
                    newAnswear.Options.clear()
                else:
                    newAnswear = Answer(Question=question, Survey=form.instance)
                    newAnswear.save()
                if question.InputType.pk == settings.TEXT_ID:
                    newAnswear.Text =  request.get(str(question.pk))
                if question.InputType.pk == settings.NUMERIC_ID:
                    newAnswear.Numeric = request.get(str(question.pk))
                if question.InputType.pk == settings.BOOL_ID:
                    newAnswear.Bool = bool(int(request.get(str(question.pk))))
                if question.InputType.pk == settings.OPTIONS_ID:
                    for option in request.getlist(str(question.pk)):
                        selectedOption = GetOption(option)
                        newAnswear.Options.add(selectedOption)
                newAnswear.save()
            else:
                if Answer.objects.filter(Question = question.pk, Survey = form.instance.pk).exists():
                    Answer.objects.filter(Question = question.pk, Survey = form.instance.pk).delete()
            
        return super(FillSurvey, self).form_valid(form)



class AllSurveys(ListView):
    model = Survey
    template_name = "Survey/AllSurveys.html"
    context_object_name = "Surveys"

    
class NewQuestion(CreateView):
    model = Question
    fields = '__all__'
    template_name = 'Survey/CreateUpdateQuestion.html'
    context_object_name = 'Question'
    success_url="/Survey/"

    def form_valid(self, form):
        if form.instance.InputType.pk == settings.OPTIONS_ID:
            
            newOptionGroup = OptionGroup(Name = form.instance.Text + ' Answer Group')
            newOptionGroup.save()
            for option in GetFormOptions(self.request):
                newOption = Option(Value = option)
                newOption.save()
                newOptionGroup.Options.add(newOption)            
            newOptionGroup.save()
            form.instance.OptionGroup = newOptionGroup
            form.save()
            return super(NewQuestion, self).form_valid(form)


        return super(NewQuestion, self).form_valid(form)

    def form_invalid(self, form):
        print('Form was invalid')
        return super(NewQuestion, self).form_invalid(form)


class UpdateQuestion(UpdateView):
    model = Question
    template_name = 'Survey/CreateUpdateQuestion.html'
    context_object_name = 'Question'
    success_url="/Survey/"
    fields = '__all__'

    def form_valid(self, form):
        if form.instance.InputType.pk == settings.OPTIONS_ID:
            formOptions = GetFormOptions(self.request)
            instanceOptionGroup = GetInstanceOptionGroup(form)
            if instanceOptionGroup != None:
                for option in instanceOptionGroup.Options.all():
                    if option.Value in formOptions:
                        formOptions.remove(option.Value)
                    else:
                        instanceOptionGroup.Options.remove(option)
                        option.delete(keep_parents=True)
            else:
                instanceOptionGroup = OptionGroup(Name=form.instance.Text + "Answer Group")
                instanceOptionGroup.save()
                form.instance.OptionGroup = instanceOptionGroup

            for newOption in formOptions:
                newOptionObject = Option(Value = newOption)
                newOptionObject.save()
                instanceOptionGroup.Options.add(newOptionObject)
            
            instanceOptionGroup.save()
            form.instance.OptionGroup = instanceOptionGroup
            form.save()
            return super(UpdateQuestion, self).form_valid(form)
        else:
            return super(UpdateQuestion, self).form_valid(form)




class ViewQuestion(DetailView):
    model = Question
    template_name = "Survey/ViewQuestion.html"
    context_object_name = 'Question'

class AllQuestions(ListView):
    model = Question
    template_name = "Survey/AllQuestions.html"
    context_object_name = 'Questions'

templates/Survey/AllQuestions.html
{% extends "base.html" %}
{% load staticfiles %}
{% block custom_css %}

        <link rel="stylesheet" href="{% static 'CSS/Survey/Questions.css' %}">

{% endblock custom_css %}

{% block body_block %}

    
    <div class="container">
        <h1>Questions registed in the system</h1>
        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>Type:</th>
                    <th>Question:</th>
                    <th>Mandatory</th>
                    <th colspan="3">Modify</th>
                </tr>
            </thead>
            <tbody>
                {% for question in Questions %}
                <tr>
                    <td>{{question.InputType.Name}}</td>
                    <td>{{question.Text}}</td>
                    <td class="icon">
                        {% if question.AnswerRequired %}
                            <i class="fa fa-check" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-times" aria-hidden="true"></i>
                        {% endif %} 
                    </td>
                    <td><a href="{% url 'Survey:Details' pk=question.pk %}">Details</a></td>
                    <td><a href="{% url 'Survey:Edit' pk=question.pk %}">Edit</a></td>
                    <td><a href="#">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
    

{% endblock body_block %}

templates/Survey/AllSurveys.html
{% extends "base.html" %}

{% block body_block %}

    <div class="container">
        
        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>Engagement:</th>
                    <th>Question Set</th>
                    <th>Progress</th>
                    <th>Partake</th>
                </tr>
            </thead>
            <tbody>
                {% for survey in Surveys %}
                    <tr>
                        <td>{{survey.Engagement.Name}}</td>
                        <td>{{survey.QuestionSet.Name}}</td>
                        <td>{{survey.answer_set.count}}/{{survey.QuestionSet.Questions.count}}</td>
                        <td><a href="{% url 'Survey:Survey' pk=survey.pk %}">[Fill in]</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>    

{% endblock body_block %}

templates/Survey/CreateSurvey.html
{% extends "base.html" %}
{% load staticfiles %}
{% block custom_css %}

        <link rel="stylesheet" href="{% static 'CSS/Survey/Questions.css' %}">

{% endblock custom_css %}

{% block body_block %}

    
    <div class="container">
      
       
       <form method="POST">
           {% csrf_token %}
           <legend>Create a survey</legend>
            {% if messages %}
            <ul class="bg-danger">
                {% for message in messages %}
                <li{% if message.tags %} class="bg-danger"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
           <div class="form-group">

               <label for="id_Name">Survey name</label>
               {{form.Name}}
               <label for="id_DefaultFor">Default survey for:</label>
               {{form.DefaultFor}}
           </div>
       
        <button type="submit" class="btn btn-primary">Create a Survey Model</button>

        <h1>Questions registed in the system</h1>
        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>Add?</th>
                    <th>Type:</th>
                    <th>Question:</th>
                    <th>Mandatory</th>
                </tr>
            </thead>
            <tbody>
                {% for question in view.Questions %}
                <tr>
                    <td><input id="q{{question.pk}}" type="checkbox" name="selectedQuestions" value="{{question.pk}}"></td>
                    <td>{{question.InputType.Name}}</td>
                    <td>{{question.Text}}</td>
                    <td class="icon">
                        {% if question.AnswerRequired %}
                            <i class="fa fa-check" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-times" aria-hidden="true"></i>
                        {% endif %} 
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
       </form> 
    </div>
    

{% endblock body_block %}

templates/Survey/CreateUpdateQuestion.html
{% extends "base.html" %}

{% block custom_scripts %}      

<script>
$(function() {
        var selected = $("#id_InputType").val();
        $("#AddButton").toggle(selected == '{{OPTIONS}}');
        $("#Options").toggle(selected == '{{OPTIONS}}');
        $('#mChoice').toggle(selected =='{{OPTIONS}}');
    })


$(function() {
        $("#id_InputType").change(function () {
            var selected = this.value
            $("#AddButton").toggle(selected == '{{OPTIONS}}');
            $("#Options").toggle(selected == '{{OPTIONS}}');
            $('#mChoice').toggle(selected =='{{OPTIONS}}');
    })
});

$(function() {
    $("#id_InputType").change(function () {
            var selected = this.value
        $("#Unit").toggle(selected == '{{NUMERIC}}');

    })
});

$(document).ready(function() {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $("#OptionList"); //Fields wrapper
    var add_button      = $("#AddButton"); //Add button ID
    
    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<li><input type="text" name="Options"/><a href="#" class="remove_field">Remove</a></li>'); //add input box
        }
    });
    
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('li').remove(); x--;
    })
});

</script>

{% endblock custom_scripts %}       

{% block body_block %}


<div class="container">
    {% if Question.pk is None %}
        <h1>Create Question</h1>
    {% else %}
        <h1>Update Question</h1>
    {% endif %}

    <form id="QuestionForm" method="POST">
            {% csrf_token %}
            
            <table class="table table-striped table-hover">            
                <tr>
                    <td>Question:</td>
                    <td>{{form.Text}}</td>
                </tr>
                <tr>    
                    <td>Input Type</td>
                    <td>{{form.InputType}}
                        <button type="button" class="btn btn-info" id="AddButton" style="display:none">Add</button>
                    </td>
                </tr>
                <tr>
                    <td>Question Section</td>
                    <td>{{form.Section}}</td>
                </tr>
                <tr>
                    <td>Answer Required?</td>
                    <td>{{form.AnswerRequired}}</td>
                </tr>
                <tr id="mChoice" style="display:none">
                    <td>Multi choice?</td>
                    <td>{{form.MultipleAnswers}}</td>
                </tr>
                <tr id="Unit" style="display:none">
                    <td>
                        Unit:
                    </td>
                    <td>
                        {{form.Unit}}
                    </td>
                </tr>
                <tr id="Options" style="display:none">
                    <td> 
                        <p> Options: </p> 
                    </td>
                    <td>
                            {% if Question.pk is None %}
                                <ul id="OptionList" class="list-group" >
                            
                                </ul>
                            {% else %}
                                 <ul id="OptionList" class="list-group" >
                                {% for option in Question.OptionGroup.Options.all %}
                                    <li><input type="text" name="Options" value="{{option.Value}}" /><a href="#" class="remove_field">Remove</a></li>
                                {% endfor %}
                                 </ul>
                            {% endif %}

                    </td>
                <tr>
                    <td colspan="2" align = "center">
                        <input type="Submit" name="btn-primary" value="Submit!">
                    </td>
                </tr>
            </table>

        </form>

</div>
{% endblock body_block %}

templates/Survey/Survey.html
{% extends "base.html" %}
{% load SurveyExtras %}
{% block body_block %}
    
    <div class="container">
        <h1>{{Survey.Name}}</h1>

        {% if request.user == Survey.Respondent %}
        
            <form method="POST">
            {% csrf_token %}
            {% for question in Survey.QuestionSet.Questions.all  %}
            
                
                <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
                    
                    <div class="row">
                        
                        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
                            <h3>{{question.Text}}</h3>
                        </div>
                        
                    </div>
                    

                
                
                {% if question.InputType.pk == OPTIONS %}
                
                    {% with input_type=question.MultipleAnswers|input_type message=question.MultipleAnswers|message %}
                    

                        <div class="row">
                            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                                <p class="center-block">{{message}}</p>
                            </div> 
                            
                            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                            {% for option in question.OptionGroup.Options.all %}
                                    
                                    <div class="row">
                                        
                                        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                                            <input id="{{option.pk}}" type="{{input_type}}" name="{{question.pk}}" value="{{option.Value}}" 
                                            {% for answer in view.Answers %}
                                                {% if answer.Question.pk == question.pk %}
                                                    {% if option in answer.Options.all %}
                                                        checked
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %} 
                                            />
                                        </div>
                                        
                                        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                                            <label for="{{option.pk}}">{{option.Value}}</label>
                                        </div>
                                        
                                    </div>
                                    
                            {% endfor %} 
                            
                            
                            </div>     
                        </div>           
                    {% endwith %}
                {% elif question.InputType.pk == TEXT %}

                    <div class="row">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                            <p>Specify your answer here:</p>
                        </div> 
                        
                        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                        
                            <textarea name="{{question.pk}}" class="form-control" rows=5 >{% for answer in view.Answers %}{% if answer.Question.pk == question.pk %}{{answer.Text}}{% endif %}{% endfor %}</textarea>
                                    
                        </div>

                    </div>                                
                {% elif question.InputType.pk == BOOL %}

                    <div class="row">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                            <p>True/False question <br> Select one:</p>
                        </div> 
                        
                        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                        
                            <div class="row">
                                
                                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                                    <input id="{{question.pk}} TRUE" type="radio" name="{{question.pk}}" {% for answer in view.Answers %}{% if answer.Question.pk == question.pk %}{% if answer.Bool %}checked{% endif %}{% endif %}{% endfor %} value=1 />
                                </div>
                                
                                <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                                    <label for="{{question.pk}} TRUE">Yes</label>
                                </div>
                                
                            </div>
                            <div class="row">
                                
                                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                                    <input id="{{question.pk}} False" type="radio" name="{{question.pk}}" {% for answer in view.Answers %}{% if answer.Question.pk == question.pk %}{% if not answer.Bool %}checked{% endif %}{% endif %}{% endfor %} value=0 />
                                </div>
                                
                                <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                                    <label for="{{question.pk}} False">No</label>
                                </div>
                                
                            </div>                                
                        </div>
                    </div>   
                {% elif question.InputType.pk == NUMERIC %}

                    <div class="row">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                            <p>Specify your answer here:</p>
                        </div> 
                        
                        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                        
                            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                <input type="number" name="{{question.pk}}" value={% for answer in view.Answers %}{% if answer.Question.pk == question.pk %}{{answer.Numeric}}{% endif %}{% endfor %}>
                            </div>
                            
                            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                                <p>{{question.Unit.Name}}</p>
                            </div>
                            
                                
                        </div>

                    </div>                                

                {% endif %}
            </div>
            {% endfor %}
            
            <div class="row">
                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                    <input type="Submit" value="Post Results"/>   
                </div>         
            </div>

            </form>
        {% else %}
            
            <div class="jumbotron">
                <div class="container">
                    <h2>Hey... you are not supposed to be here!</h2>
                    <img src="http://clipartview.com/wp-content/uploads/2017/03/policeman-stop-clipart.png" height="200opx">
                    <p>this Survey is to be filled in by: {{Survey.Respondent.get_full_name}}</p>
                    <p>
                        <a class="btn btn-primary btn-lg" href="{% url 'Demand:Index' %}">Scoot along now, back to homepage with ya...</a>
                    </p>
                </div>
            </div>
            
        {% endif %}
    </div>
{% endblock body_block  %}

templates/Survey/ViewQuestion.html
{% extends "base.html" %}

{% block body_block %}

    
    <div class="container">
        
        <h1>Question Details</h1>
        
        <div class="table-responsive">
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <td>Questions</td>
                        <td>{{Question.Text}}</td>
                    </tr>
                    <tr>
                        <td>Type: </td>
                        <td>{{Question.InputType.Name}}</td>
                    </tr>
                    <tr>
                        <td>Mandatory?</td>
                        <td>{{Question.AnswerRequired}}</td>
                    </tr>
                    {% if Question.InputType.pk == OPTIONS %}
                    
                        <tr>
                            <td>Multi Choice?</td>
                            <td> {{Question.MultipleAnswers}} </td>
                        </tr>

                        <tr>
                            <td rowspan="{{Question.OptionGroup.Options.all.count}}">Options:</td>
                            {% for option in Question.OptionGroup.Options.all %}
                                <td>{{option.Value}}</td>
                                </tr>
                            {% endfor %}
                        </tr>

                    {% elif Question.InputType.pk == NUMERIC %}
                        {% if not Question.Unit is None %}
                            <tr>
                                <td>Unit:</td>
                                <td>{{Question.Unit.Name}}</td>
                            </tr>
                        {% endif %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        

    </div>
    

{% endblock body_block %}