Demand/urls.py
from django.conf.urls import url
from views import  DemandCreateView, DemandListView

app_name = 'Demand'

urlpatterns = [
    url(r'^$', DemandListView.as_view(), name="Index"),
    url(r'^Create/', DemandCreateView.as_view(), name="Create")

]

DemandManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from Demand.views import MainPage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'), 
    url(r'^$', MainPage.as_view(), name='Welcome'),
    url(r'^DemandManagement/', include('Demand.urls')),
    url(r'^Engagement/', include('Engagement.urls')),
    url(r'^Survey/', include('Survey.urls')),
]

Engagement/urls.py
from django.conf.urls import url
from views import  SubProjectListView, SubProjectDetailView, SubProjectMyListView, NextStatus, PreviousStatus, SubProjectMyInactive, SubprojectActivate, ChangeProjectStauts, AddNote, DeleteNote
app_name = 'Engagement'

urlpatterns = [
    url(r'^$', SubProjectListView.as_view(), name="Index"),
    url(r'^MyEngagements/$', SubProjectMyListView.as_view(), name="MyProjects"),
    url(r'^(?P<pk>\d+)/$', SubProjectDetailView.as_view(), name='Detail'),
    url(r'^Inactive/$',  SubProjectMyInactive.as_view(), name='Inactive'),
    url(r'^Activate/(?P<pk>\d+)/$', SubprojectActivate.as_view(), name='Activate'),
    url(r'^NextStatus/(?P<pk>\d+)/$', NextStatus, name='NextStatus'),
    url(r'^PreviousStatus/(?P<pk>\d+)/$', PreviousStatus, name='PreviousStatus'),
    url(r'^ReactivateProject/(?P<pk>\d+)/(?P<status>[\w ]+)/$', ChangeProjectStauts, name='ChangeProject'),
    url(r'^NewNote/(?P<pk>\d+)/$', AddNote, name='AddNote'),
    url(r'^DeleteNote/(?P<pk>\d+)/$', DeleteNote, name='DeleteNote'),
]

Demand/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Status(models.Model):
    Name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Statuses"
    def __str__(self):
        return self.Name

class Risk(models.Model):
    Name = models.CharField(max_length=50)
    def __str__(self):
        return self.Name
    

class BusinessPriority(models.Model):
    Name = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural = "BusinessPriorities"
    
    def __str__(self):
        return self.Name

class Category(models.Model):
    Code = models.IntegerField()
    Name = models.CharField(max_length=255)
    #Projects = models.ManyToManyField(Project, blank=True)
    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.Code) + ' - ' + self.Name
class Region(models.Model):
    Name = models.CharField(max_length = 100)
    def __str__(self):
        return self.Name

class Country(models.Model):
    Name = models.CharField(max_length = 100)
    Region = models.ForeignKey(Region)
    class Meta:
        verbose_name_plural = "Countries"
    def __str__(self):
        return self.Name
class Activity(models.Model):
    Name = models.CharField(max_length=255)
    Description = models.CharField(max_length=1000)
    Manager = models.ForeignKey(User)
    class Meta:
        verbose_name_plural = "Activities"
    def __str__(self):
        return self.Name

class Project(models.Model):
    Name = models.CharField(max_length = 256)
    Owner = models.ForeignKey(User)
    Status = models.ForeignKey(Status)    
    Risk = models.ForeignKey(Risk)
    Categories = models.ManyToManyField(Category, blank=True)
    Countries = models.ManyToManyField(Country, blank=True)
    BusinessPriority = models.ForeignKey(BusinessPriority, verbose_name= 'Business Priority')
    Spend = models.FloatField(blank=True, default=0)
    Savings = models.FloatField(blank=True, default=0)
    StartDate = models.DateField( verbose_name= 'Project Start Date')
    EndDate = models.DateField( verbose_name= 'Project End Date')
    LastUpadate = models.DateTimeField(auto_now=True, blank=True)
    Activities = models.ManyToManyField(Activity, blank=True, related_name='activities')
    Comments = models.CharField(max_length=1000, blank=True)
    Actions = models.CharField(max_length=255, blank=True)
    BusinessContacts = models.ManyToManyField(User, blank = True, related_name='BusinessContacts')
    BusinessPartners = models.ManyToManyField(User, blank = True, related_name='BusinessPartners')

    def __str__(self):
        return self.Name
    def GetSubProjects(self):
        return self.subproject_set.filter(Active=True)


class UserAssosiation(User):

    user = models.OneToOneField(User)


    def __str__(self):
        return self.user.username

Demand/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.admin.widgets import AdminDateWidget
from Demand.models import Project, Category
from Engagement.models import SubProject, Step, SubStatus, Activity, ProjectManagement
import datetime
from math import floor
# Create your views here.


def GetStep(stepID):
    return Step.objects.get(pk=stepID)

def GetSubStatus(substatusId):
    return SubStatus.objects.get(pk=substatusId)

def GetProject(projectId):
    return Project.objects.get(pk=projectId)

def GetActivity(activityId):
    return Activity.objects.get(pk=activityId)

def GetCategory(categoryId):
    return Category.objects.get(pk=categoryId)

def SplitWorkdays(startDate, endDate, count):
    daygenerator = (startDate + datetime.timedelta(x+1) for x in xrange((endDate - startDate).days))
    dayList = [ day for day in daygenerator if day.weekday() < 5]
    dayCount = len(dayList)

    dayDelta = floor(dayCount/count)
    Periods = []
    timePeriod = []
    i=0
    for day in dayList:
        if timePeriod == []:
            timePeriod.append(day)
            i=0
        if i==dayDelta-1:
            timePeriod.append(day)
            Periods.append(timePeriod)
            timePeriod = []
        else:
            i+=1
    return Periods


class DemandListView(ListView):
    model = Project
    template_name = 'Demand/index.html'
    context_object_name = 'Projects'


class MainPage(TemplateView):
    template_name = 'index.html'

class DemandCreateView(CreateView):
    model = Project
    template_name = 'Demand/create.html'
    fields = [
        'Name',
        'Owner',
        'Status',
        'Risk',
        'Categories',
        'Countries',
        'BusinessPriority',
        'Spend',
        'Savings',
        'StartDate',
        'EndDate',
        'Activities',
        'Comments',
        'Actions',
    ]
    
    success_url="/DemandManagement/"

    def form_valid(self, form):
        formEndDate = form.instance.EndDate
        form.save()
        #Saving the form for it to have a PK so I can assign it to its children
        formParent = form.instance.pk
        for activity in self.request.POST.getlist('Activities'):
            SB = SubProject(Name='[' + form.instance.Name + '] ' + GetActivity(activity).Name, Active=False, Activity=GetActivity(activity), Project = GetProject(formParent), Requestor=form.instance.Owner, Step=GetStep(1), Deadline=formEndDate, Status=GetSubStatus(1))
            SB.save()
            for category in self.request.POST.getlist('Categories'):
                SB.Categories.add(GetCategory(category))
            StepsForThisActivity = Step.objects.filter(Activity = GetActivity(activity))
            PeriodList = SplitWorkdays(form.instance.StartDate, form.instance.EndDate, len(StepsForThisActivity))
            i=0
            for step in StepsForThisActivity:
                PM = ProjectManagement(Completed = False,Step= step, SubProject=SB, StartDate=PeriodList[i][0], EndDate=PeriodList[i][1], )
                PM.save()
                i+=1
            SB.save()

        return super(DemandCreateView, self).form_valid(form)

templates/Demand/create.html
{% extends "base.html" %}
{% block custom_scripts %}
<script>
$(function() {
        $( "#id_StartDate, #id_EndDate, id_LastUpadate" ).datepicker({
                dateFormat: "yy-mm-dd",
                defaultDate: "+1w",
                changeMonth: true,
                numberOfMonths: 1,
                onClose: function( selectedDate ) {
                        $( "#id_birth_date" ).datepicker( "option", "minDate", selectedDate );
                }
        });
});
</script>
{% endblock custom_scripts %}

{% block body_block  %}

    <form method="POST">
        {% csrf_token %}
        
        <table class="table table-hover">
            {{form.as_table}}
        </table>

        <input type="Submit" name="btn-primary" value="Submit!">
    </form>

{% endblock body_block  %}

templates/Demand/index.html
{% extends "base.html" %}

{% block body_block  %}

<div class="container">
    
    
    <form action="{% url 'Demand:Create' %}" >    
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    
    
    <h1>Currently Created Demand</h1>
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Owner</th>
                <th>Status</th>
                <th>Categories</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Spend</th>
                <th>Savings</th>
                <th>Active Projects</th>
            </tr>
        </thead>
        <tbody>
            {% for project in Projects %}
            <tr>
                <td>{{project.Name}}</td>
                <td>{{project.Owner.get_full_name}}</td>
                <td>{{project.Status}}</td>
                <td>
                    <ul class="list-group">
                        {% for category in project.Categories.all %}    
                            <li class="list-group-item">{{category}}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>{{project.StartDate}}</td>
                <td>{{project.EndDate}}</td>
                <td>{{project.Spend}}</td>
                <td>{{project.Savings}}</td>
                <td>
                    <ul class="list-group">
                        {% for subproject in project.GetSubProjects %}    
                            <li class="list-group-item">
                                <a href="{% url 'Engagement:Detail' pk=subproject.pk %}">
                                    <i class="fa fa-cubes" aria-hidden="true"></i>
                                    {{subproject.Activity}}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    



</div>

{% endblock body_block  %}