Demand/urls.py
from django.conf.urls import url
from views import  DemandCreateView, DemandListView

app_name = 'Demand'

urlpatterns = [
    url(r'^$', DemandListView.as_view(), name="Index"),
    url(r'^Create/', DemandCreateView.as_view(), name="Create")

]

DemandManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from Demand.views import MainPage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'), 
    url(r'^$', MainPage.as_view(), name='Welcome'),
    url(r'^DemandManagement/', include('Demand.urls')),
    url(r'^Engagement/', include('Engagement.urls')),
    url(r'^Survey/', include('Survey.urls')),
]

Engagement/urls.py
from django.conf.urls import url
from views import  SubProjectListView, SubProjectDetailView, SubProjectMyListView, NextStatus, PreviousStatus, SubProjectMyInactive, SubprojectActivate, ChangeProjectStauts, AddNote, DeleteNote
app_name = 'Engagement'

urlpatterns = [
    url(r'^$', SubProjectListView.as_view(), name="Index"),
    url(r'^MyEngagements/$', SubProjectMyListView.as_view(), name="MyProjects"),
    url(r'^(?P<pk>\d+)/$', SubProjectDetailView.as_view(), name='Detail'),
    url(r'^Inactive/$',  SubProjectMyInactive.as_view(), name='Inactive'),
    url(r'^Activate/(?P<pk>\d+)/$', SubprojectActivate.as_view(), name='Activate'),
    url(r'^NextStatus/(?P<pk>\d+)/$', NextStatus, name='NextStatus'),
    url(r'^PreviousStatus/(?P<pk>\d+)/$', PreviousStatus, name='PreviousStatus'),
    url(r'^ReactivateProject/(?P<pk>\d+)/(?P<status>[\w ]+)/$', ChangeProjectStauts, name='ChangeProject'),
    url(r'^NewNote/(?P<pk>\d+)/$', AddNote, name='AddNote'),
    url(r'^DeleteNote/(?P<pk>\d+)/$', DeleteNote, name='DeleteNote'),
]

Engagement/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.core import serializers
from Demand.models import Category, BusinessPriority, Activity, Project
from collections import OrderedDict
from itertools import chain
import datetime
import re
import operator


class SetArea(models.Model):
    Name = models.CharField(max_length=256)
    class Meta:
        verbose_name_plural = 'SetAreas'
    def __str__(self):
        return self.Name


class RequestType(models.Model):
    Name = models.CharField(max_length=256)
    Activity = models.ForeignKey(Activity)
    class Meta:
        verbose_name_plural = 'RequestTypes'
    def __str__(self):
        return self.Name + ' - ' + self.Activity.Name

class Complexity(models.Model):
    Name =models.CharField(max_length=10)
    class Meta:
        verbose_name_plural = 'Complexities'
    def __str__(self):
        return self.Name

class SubStatus(models.Model):
    Name = models.CharField(max_length=100)
    class Meta: 
        verbose_name_plural = 'SubStatuses'
    def __str__(self):
        return self.Name

class Step(models.Model):
    Order = models.PositiveIntegerField()
    Name = models.CharField(max_length=256)
    Activity = models.ForeignKey(Activity)
    class Meta:
        verbose_name_plural = 'Steps'
    def __str__(self):
        return self.Activity.Name + ' - ' + self.Name
    

class SubProject(models.Model):
    Project = models.ForeignKey(Project,null=True)
    Activity = models.ForeignKey(Activity, null=True)
    Active = models.BooleanField()
    CreatedDate = models.DateTimeField(auto_now_add=True)
    LastUpdated = models.DateTimeField(auto_now=True)
    Requestor = models.ForeignKey(User, related_name='Requestor')
    ForSetArea = models.ForeignKey(SetArea, null=True )
    Name = models.CharField(max_length=256, null=True)
    Step = models.ForeignKey(Step)
    Categories = models.ManyToManyField(Category, blank=True)
    Specialist = models.ForeignKey(User, related_name='Specialist', null=True)
    Type = models.ForeignKey(RequestType,null=True)
    Complexity = models.ForeignKey(Complexity,blank=False, null=True)
    Details = models.CharField(max_length=1000, blank=True)
    Priority = models.ForeignKey(BusinessPriority,null=True)
    Deadline = models.DateField(null=True, blank=True)
    AdjustedDeadline = models.DateField(blank=True, null=True)
    Status = models.ForeignKey(SubStatus)
    Completed = models.DateField(blank=True, null=True)
    Comments = models.CharField(max_length=1000, blank=True)
    class Meta:
        verbose_name_plural = 'SubProjects'
    def __str__(self):
        if self.Name == None:
            return '-'
        else:
            return self.Name
    def GenerateUserSuggestions(self):
        startDate = self.Project.StartDate
        endDate = self.Project.EndDate

        collidingProjects = Project.objects.exclude(EndDate__lte = startDate).exclude(StartDate__gte = endDate)
        collidingEngagements = []
        for project in collidingProjects:
            collidingEngagements = chain(collidingEngagements, project.subproject_set.filter(Active=True))
        
        busyUsers = {}
        complexityDict = {
            "High" : 3,
            "Medium" : 2, 
            "Low": 1,
            "None": 0
        }
        for project in collidingEngagements:
            if not project.Specialist in busyUsers:
                busyUsers[project.Specialist] = complexityDict[str(project.Complexity)]
            else:
                busyUsers[project.Specialist] += complexityDict[str(project.Complexity)]
        busyUsers = OrderedDict(sorted(busyUsers.items(), key=lambda t: t[1], reverse=True))
        return busyUsers

    def GenerateGanntValues(self):
        phases =  self.projectmanagement_set.all()
        output = '['
        previous = 'null'
        for phase in phases:
            if phase == phases[len(phases)-1]:
                end = ']'
            else: 
                end = '], '
            output = output + "['" + str(phase.Step.Order) + "', " 
            output = output + "'" + phase.Step.Name + "'"  + ', '
            output = output + 'new Date(' +str(phase.StartDate.year) + ', ' + str(phase.StartDate.month-1) + ', ' + str(phase.StartDate.day) + '), '
            output = output + 'new Date(' + str(phase.EndDate.year) + ', ' + str(phase.EndDate.month-1) + ', ' + str(phase.EndDate.day) + '), '
            output = output + 'daysToMilliseconds(' + str((phase.EndDate - phase.StartDate).days) + '), '
            output = output + str(phase.Completed * 100) + ', '
            output = output + previous if previous == 'null' else output + "'" + previous + "'"
            output = output + end
            previous =  str(phase.Step.Order)
        output = output + ']'
        output = output.decode()
        output = output.encode(encoding='utf8')
        return output
    def GenerateGanttJSON(self):
        phases = self.projectmanagement_set.all()
        data = serializers.serialize('json', phases)
        return data
        
# Create your models here.
class ProjectManagement(models.Model):
    Completed = models.BooleanField(default=False)
    Step = models.ForeignKey(Step)
    CreatedDate = models.DateTimeField(auto_now_add=True)
    LastUpdated = models.DateTimeField(auto_now=True)
    SubProject = models.ForeignKey(SubProject)
    StartDate = models.DateField(blank=True, null=True)
    EndDate = models.DateField(blank=True, null=True)
    Comments = models.CharField(max_length=1000, blank=True)
    class Meta:
        verbose_name_plural = 'ProjectManagementActivities'    
    def __str__(self):
        return self.Step.Name 
    

class Note(models.Model):
    CreatedDate = models.DateTimeField(auto_now_add=True)
    Engagement = models.ForeignKey(SubProject)
    Text = models.TextField(max_length=10000)

class EventLog(models.Model):
    CreatedDate = models.DateTimeField(auto_now_add=True)
    By = models.ForeignKey(User)
    Action = models.TextField(max_length=256)
    Engagement = models.ForeignKey(SubProject)

Engagement/views.py
from django.views.generic import ListView, DetailView, TemplateView, UpdateView
from django.shortcuts import get_object_or_404, redirect, reverse
from Engagement.models import SubProject, SubStatus, Activity, Note, EventLog
from django.contrib.auth.models import User
from .forms import DeleteNoteForm 

# Create your views here.

def GetSubStatus(name):
    return get_object_or_404(SubStatus, Name=name)

class SubProjectListView(ListView):
    model=SubProject
    template_name = 'Engagement/index.html'
    context_object_name = 'SubProjects'
    def get_queryset(self):
        MyProjects =SubProject.objects.filter(Active=True)
        return MyProjects


class SubProjectMyListView(ListView):
    template_name= 'Engagement/index.html'
    context_object_name = 'SubProjects'

    def get_queryset(self):
        currentUser = self.request.user
        if currentUser.is_authenticated():
            MyProjects =SubProject.objects.filter(Specialist=currentUser)
            return MyProjects
        return None


class SubProjectMyInactive(ListView):
    template_name= 'Engagement/index.html'
    context_object_name = 'SubProjects'
    
    def get_queryset(self):
        UserManagedActivities = Activity.objects.filter(Manager=self.request.user)
        MyProjects = SubProject.objects.filter(Active= False, Activity__in = UserManagedActivities)
        return MyProjects

class SubprojectActivate(UpdateView):
    model = SubProject
    template_name = 'Engagement/edit.html'
    fields = (
        'Active',
        'ForSetArea',
        'Name',
        'Complexity',
        'Step',
        'Categories',
        'Specialist',
        'Type',
        'Details',
        'AdjustedDeadline',
        'Status',
        'Comments'
    )
    success_url="/Engagement/Inactive/"
    context_object_name = 'SubProject'
    
class SubProjectDetailView(DetailView):
    model = SubProject
    template_name= 'Engagement/details.html'
    context_object_name = 'SubProject'

def AddNote(request, pk):
    thisProject = get_object_or_404(SubProject, pk=pk)
    newNote = Note(Engagement=thisProject, Text=request.POST['Note'])
    newNote.save()
    return redirect(request.META['HTTP_REFERER'])

def DeleteNote(request, pk):
    
    thisNote = get_object_or_404(Note, pk=pk)
    form = DeleteNoteForm(request.POST, instance=thisNote)
    if request.method == 'POST':
        if form.is_valid():
            thisNote.delete()
            return redirect(request.META['HTTP_REFERER'])
    return redirect('/Engagement/')

def NextStatus(request, pk):
    thisProject = get_object_or_404(SubProject, pk=pk)
    projectStatus = thisProject.Status.pk
    if projectStatus >= 1 and projectStatus < 3:
        thisProject.Status = get_object_or_404(SubStatus, pk=projectStatus+1)
        thisProject.save()
        newLog = EventLog(Engagement=thisProject, By=request.user, Action="Uplifeted the status to: " + str(thisProject.Status))
        newLog.save()
    return redirect(request.META['HTTP_REFERER'])


def PreviousStatus(request, pk):
    thisProject = get_object_or_404(SubProject, pk=pk)
    projectStatus = thisProject.Status.pk
    if projectStatus > 1 and projectStatus <= 3:
        thisProject.Status = get_object_or_404(SubStatus, pk=projectStatus-1)
        thisProject.save()
        newLog = EventLog(Engagement=thisProject, By=request.user, Action="Downgraded the status to: " + str(thisProject.Status))
        newLog.save()
    return redirect(request.META['HTTP_REFERER'])

def ChangeProjectStauts(request, pk, status):
    thisProject = get_object_or_404(SubProject, pk=pk)
    thisProject.Status = GetSubStatus(status) 
    thisProject.save()
    newLog = EventLog(Engagement=thisProject, By=request.user, Action="Changed the status to: " + str(thisProject.Status))
    newLog.save()
    return redirect(request.META['HTTP_REFERER'])

templates/Engagement/details.html
{% extends "base.html" %}

{% block custom_scripts %}
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawChart);

    function daysToMilliseconds(days) {
      return days * 24 * 60 * 60 * 1000;
    }

    function drawChart() {
      var source = {{SubProject.GenerateGanntValues|safe}};
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Task ID');
      data.addColumn('string', 'Task Name');
      data.addColumn('date', 'Start Date');
      data.addColumn('date', 'End Date');
      data.addColumn('number', 'Duration');
      data.addColumn('number', 'Percent Complete');
      data.addColumn('string', 'Dependencies');

      data.addRows(source);
      var options = {
        height: 300,
                
        labelStyle: {
          fontSize: 14,
          color: '#757575'
        },        
      };

      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));

      chart.draw(data, options);
    }
  </script>
{% endblock custom_scripts %}

{% block body_block %}
  
  <div class="container">
    
  
  
    <h1> {{SubProject.Name}}</h1>
    <h2> Project Details </h2>
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#Home" data-toggle="tab">Project Details</a>
      </li>
      {% if user.pk == SubProject.Specialist.pk  %}
        <li>
          <a href="#Notes" data-toggle="tab">Notes</a>
        </li>
      {% endif%}
      <li>
        <a href="#Log" data-toggle="tab">Event Log</a>
      </li>
    </ul>    
    <div class="tab-content">
      <div id="Home" class="tab-pane fade in active">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Field</th>
              <th>Details</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td> <b> Demand Info </b></td>
              <td>{{SubProject.Project.Name}}</td>
              <td> <b> Spend </b> </td>
              <td>{{SubProject.Project.Spend}}</td>
              <td> <b> Savings </b> </td>
              <td>{{SubProject.Project.Savings}}</td>
              <td> <b> End Date </b></td>
              <td>{{SubProject.Project.EndDate}}</td>
            </tr>
            <tr>
              <td>
                <b> Engagement Type </b>
              </td>
              <td> 
                {{SubProject.Activity.Name}}
              </td>
            </tr>
            <tr>
              <td>
                <b> Requestor </b>
              </td>
              <td>
                  <b> PRID </b>
              </td>
              <td>
                {{SubProject.Requestor}}
              </td>
              <td>
                  <b> Name </b>
              </td>
              <td>
                {{SubProject.Requestor.get_full_name}}
              </td>
            </tr>
            <tr>
            <tr>
              <td>
                <b> Specialist </b>
              </td>
              <td>
                  <b> PRID </b>
              </td>
              <td>
                {{SubProject.Specialist}}
              </td>
              <td>
                  <b> Name </b>
              </td>
              <td>
                {{SubProject.Specialist.get_full_name}}
              </td>
            </tr>
            <tr>
              <td>
                <b> Status </b>
              </td>
              <td> 
                {{SubProject.Status}}
              </td>
            </tr>
          </tbody>
        </table>
        

        <h2> Project Management </h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Step</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Comments</th>

                </tr>
            </thead>
            <tbody>
                    {% for pm in SubProject.projectmanagement_set.all  %}
                    <tr>
                        <td>{{pm.Step.Name}}</td>
                        <td>{{pm.StartDate}}</td>
                        <td>{{pm.EndDate}}</td>
                        <td>{{pm.Comments}}
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
        <div id="chart_div"></div>
      </div>
      {% if user.pk == SubProject.Specialist.pk  %}

        <div class="tab-pane fade" id="Notes"> 
          <h1> Notes</h1>
          
          <form action="{% url 'Engagement:AddNote' pk=SubProject.pk %}" method="POST">
            {% csrf_token %}
            <legend>New note</legend>
            
            <div class="form-group">
              
              <textarea name="Note" id="Note" class="form-control" rows="4" required="required" placeholder="Specify your note here, only you can see this."></textarea>
              
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
          <h2> Current Notes: </h2>      
          {% for note in SubProject.note_set.all %}

            <form action="{% url 'Engagement:DeleteNote' pk=note.pk %}" method="POST">
              {% csrf_token %}
                <h4>
                  {{note.CreatedDate}}
                
                  <button type="submit" class="btn btn-danger">Delete</button>
                </h4>
            </form>
              
            <div class="well">
              <p> {{note.Text}}</p>
            </div>
          {% endfor %}
        
        </div>
      {% endif %}
      <div id="Log" class="tab-pane fade">
        <h1>Action Log:</h1>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Action time</th>
              <th>User</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for log in SubProject.eventlog_set.all  %}
              <tr>
                <td>{{log.CreatedDate}}</td>
                <td>{{log.By.get_full_name}}</td>
                <td>{{log.Action}}</td>
              </tr>            
            {% endfor %}

          </tbody>
        </table>
        {{SubProject.GenerateGanttJSON}}
      </div>
    </div>  
  </div>
{% endblock body_block %}

templates/Engagement/edit.html
{% extends "base.html" %}

{% block custom_scripts %}
<script>
$(function() {
        $( "#id_Deadline, #id_AdjustedDeadline" ).datepicker({
                dateFormat: "yy-mm-dd",
                defaultDate: "+1w",
                changeMonth: true,
                numberOfMonths: 1,
                onClose: function( selectedDate ) {
                        $( "#id_birth_date" ).datepicker( "option", "minDate", selectedDate );
                }
        });
});
</script>
{% endblock custom_scripts %}

{% block body_block %}


<div class="container">
    


    <h1>
        {% if not form.instance.pk %}
            Create Engagement
        {% else %}
            Activate Engagement
        {% endif %}
        
    </h1>
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Employee</th>
                <th>Workload</th>
            </tr>
        </thead>
        <tbody>
            {% for key, value in SubProject.GenerateUserSuggestions.items  %}
            <tr>
                <td>{{key.get_full_name}}</td>
                <td>
                    {% if value >= 10 %}
                        High
                    {% elif value < 10 and value >= 5 %}
                        Medium
                    {% else %}
                        Low                    
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <form method="POST">
        {% csrf_token %}
        {{form.as_ul}}
        <input type="Submit" name="btn-primary" value="Submit!">
    </form>
</div>
{% endblock body_block %}

templates/Engagement/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'CSS/Engagement/Engagements.css' %}">
{% endblock custom_css %}
{% block body_block %}

    
    <div class="jumbotron">
        
        <h1 class="jumbo">
            <i class="fa fa-cubes" aria-hidden="true"></i>
            Engagements Registered
        </h1>
        <p></p>
    </div>
    
    <div class="table">

        <table id="engagements" class="table table-hover table-striped" >
            <thead>
                <tr>
                    <th>Demand</th>
                    <th>Project Name</th>
                    <th>Team</th>
                    <th>Categories</th>
                    <th>Requestor</th>
                    <th>Specialist</th>
                    <th>Complexity</th>
                    <th>For Set Area</th>
                    <th>Status</th>
                    <th>Activity Type</th>
                    <th colspan="3">Deadline</th>
                </tr>
            </thead>
            <tbody>
                {% for subproject in SubProjects %}
                
                <tr>
                    <td>{{subproject.Project.Name}}</td>
                    <td><a href="{% url 'Engagement:Detail' pk=subproject.pk %}">{{subproject.Name}}</a></td>
                    <td>{{subproject.Activity}}</td>
                    <td class="toLeft">
                        <ul class="list-group">
                            {% for category in subproject.Categories.all %}    
                                <li class="list-group-item">{{category}}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{subproject.Requestor.get_full_name}}</td>
                    <td>{{subproject.Specialist.get_full_name}}</td>
                    <td>{{subproject.Complexity}}</td>
                    <td>{{subproject.ForSetArea}}</td>
                    <td>{{subproject.Status}}</td>
                    <td>{{subproject.Type}}</td>
                    <td>{{subproject.Deadline}}</td>
                    {% if request.user == subproject.Specialist %}

                        {% if subproject.Status.Name == 'Cancelled' or subproject.Status.Name == 'Suspended' or subproject.Status.Name == 'Out of scope' %}
                        
                        <td>
                        <form action="{% url 'Engagement:ChangeProject' pk=subproject.pk status='Allocated' %}" method="post">
                            {% csrf_token %}
                                <button type="submit" title="Re-Activate">
                                    <span class="glyphicon glyphicon-play-circle"></span>
                                </button> 
                        </form>
                        </td>
                        {% else %}
                        
                        <td>
                            <form action="{% url 'Engagement:NextStatus' pk=subproject.pk %}" method="post">
                                {% csrf_token %}
                                <input type="Submit" value="&#8679;" class="btn btn-default">
                            </form>
                            <form action="{% url 'Engagement:PreviousStatus' pk=subproject.pk %}" method="post">
                                {% csrf_token %}
                                <input type="Submit" value="&#8681;" class="btn btn-default">
                            </form>   
                            
                        </td>
                        <td>
                            <form action="{% url 'Engagement:ChangeProject' pk=subproject.pk status='Cancelled' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" title="Cancel">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button> 
                            </form>
                            <form action="{% url 'Engagement:ChangeProject' pk=subproject.pk status='Suspended' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" title="Suspend">
                                    <span class="glyphicon glyphicon-time"></span>
                                </button> 
                            </form>
                            <form action="{% url 'Engagement:ChangeProject' pk=subproject.pk status='Out of scope' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" title="Out of scope">
                                    <span class="glyphicon glyphicon-eye-close"></span>
                                </button> 
                            </form>
                        </td>
                        {% endif %}
                    {% else %}

                        <td></td>
                        <td></td>

                    {% endif %}

                    {% if request.user == subproject.Activity.Manager and subproject.Active == False %}
                    
                    <td>
                    <a href="{% url 'Engagement:Activate' pk=subproject.pk %}">[Activate]</a>
                    </td>

                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>



{% endblock body_block %}