Demand/urls.py
from django.conf.urls import url
from views import  DemandCreateView, DemandListView

app_name = 'Demand'

urlpatterns = [
    url(r'^$', DemandListView.as_view(), name="Index"),
    url(r'^Create/', DemandCreateView.as_view(), name="Create")

]

DemandManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from Demand.views import MainPage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'), 
    url(r'^$', MainPage.as_view(), name='Welcome'),
    url(r'^DemandManagement/', include('Demand.urls')),
    url(r'^Engagement/', include('Engagement.urls')),
    url(r'^Survey/', include('Survey.urls')),
]

Engagement/urls.py
from django.conf.urls import url
from views import  SubProjectListView, SubProjectDetailView, SubProjectMyListView, NextStatus, PreviousStatus, SubProjectMyInactive, SubprojectActivate, ChangeProjectStauts, AddNote, DeleteNote
app_name = 'Engagement'

urlpatterns = [
    url(r'^$', SubProjectListView.as_view(), name="Index"),
    url(r'^MyEngagements/$', SubProjectMyListView.as_view(), name="MyProjects"),
    url(r'^(?P<pk>\d+)/$', SubProjectDetailView.as_view(), name='Detail'),
    url(r'^Inactive/$',  SubProjectMyInactive.as_view(), name='Inactive'),
    url(r'^Activate/(?P<pk>\d+)/$', SubprojectActivate.as_view(), name='Activate'),
    url(r'^NextStatus/(?P<pk>\d+)/$', NextStatus, name='NextStatus'),
    url(r'^PreviousStatus/(?P<pk>\d+)/$', PreviousStatus, name='PreviousStatus'),
    url(r'^ReactivateProject/(?P<pk>\d+)/(?P<status>[\w ]+)/$', ChangeProjectStauts, name='ChangeProject'),
    url(r'^NewNote/(?P<pk>\d+)/$', AddNote, name='AddNote'),
    url(r'^DeleteNote/(?P<pk>\d+)/$', DeleteNote, name='DeleteNote'),
]

Survey/urls.py
from django.conf.urls import url
from views import NewQuestion, AllQuestions, ViewQuestion, UpdateQuestion, NewSurvey, FillSurvey, AllSurveys
app_name = 'Survey'

urlpatterns = [
    url(r'^$', AllSurveys.as_view(), name='Index'),
    url(r'^Create/$', NewQuestion.as_view(), name="Create"),
    url(r'^Questions/$', AllQuestions.as_view(), name='Questions'),
    url(r'^Question/(?P<pk>\d+)/$', ViewQuestion.as_view(), name='Details'),
    url(r'^Update/(?P<pk>\d+)/$',  UpdateQuestion.as_view(), name='Edit'),
    url(r'^NewSurvey/$', NewSurvey.as_view(), name='NewSurvey'),
    url(r'^Survey/(?P<pk>\d+)/$',  FillSurvey.as_view(), name='Survey'), 
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Demand Management</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Latest compiled and minified CSS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,700,800&amp;subset=latin-ext" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        {% block custom_scripts %}
        
        {% endblock custom_scripts %}
        {% block custom_css %}
        
        {% endblock custom_css %}
    </head>
    <body>
    
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'Welcome' %}">GPS Demand Management</a>
                </div>
                <div class="collapse navbar-collapse" id="main-navbar">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            
                            <a href="{% url 'Demand:Index' %}">
                                <i class="fa fa-cube" aria-hidden="true"></i>
                                Demand
                            </a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-cubes" aria-hidden="true"></i>
                                Engagements
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'Engagement:Index' %}">All Engagements</a></li>
                                <li><a href="{% url 'Engagement:MyProjects' %}">My Engagements</a></li>
                                {% if user.is_authenticated %}
                                    {% if IsManager %}
                                        <li><a href="{% url 'Engagement:Inactive' %}">Activate Engagements</a></li>   
                                    {% endif %}
                                {% endif %}
                            </ul>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-question-circle-o" aria-hidden="true"></i>
                                Survey
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'Survey:Index' %}">Index Surveys</a>
                                <li><a href="{% url 'Survey:NewSurvey' %}">Create a Question Set</a></li>
                                <li><a href="{% url 'Survey:Questions' %}">View all questions</a></li>
                            </ul>
                        </li>
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                            {% endif %}
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        
                            {% if user.is_authenticated %}
                                <li><a href=#>Hello {{user.get_full_name}} <i class="fa fa-user-circle" aria-hidden="true"></i></a></li>
                                <li><a href={% url 'logout' %}>Log off <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                            {% else %}
                                <li>Hello Stranger <i class="fa fa-user-circle" aria-hidden="true"></i> </li>
                            {% endif %}
                            
                        
                    </ul>
                </div>
            </div>
            
        </nav>
        {% block body_block %}
            
        {% endblock body_block %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block body_block  %}

<div class="container">
    
    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to Zom... Demand Management</h1>
            <p>Click the items on the main menu to procees</p>

        </div>
    </div>
    
</div>

{% endblock body_block  %}